### ISSUE TITLE
API profile page needs some content curation

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/collected-feedback#7] opened 2020-03-30 13:28 UTC
# Describe the Pain in using this API

I fail to understand:

- [ ] why description field is not by default open but I have to make additional point and click to see what this API is about
- [x] why the version information is as header. Same information is said above (just after the header which says the name of the API)
- [x] why the endpoints are list here? The value is minimal without knowing what the endpoints do and that is in API docs. In addition, another thing to update in dev portal when API changes. 

# Indicate the importance in number
(1. Critical, 2. Important, 3. Nice-to-have)

2.

**Additional context**
<img width="1293" alt="Näyttökuva 2020-3-30 kello 16 20 39" src="https://user-images.githubusercontent.com/1927158/77917641-7cf6b480-72a3-11ea-84c9-902ff89de6fd.png">

**Comment by Nazarah** [comment] 2020-03-31 05:19
@kyyberi  thanks for  your issue.

>why description field is not by default open but I have to make additional point and click to see what this API is about

This needs to be fixed from the CMS's side. I'll add an issue for the team and prioritize to fix it.

>why the version information is as header. Same information is said above (just after the header which says the name of the API)

This can also be removed, although was kept for **recognition rather than recall**.

>why the endpoints are list here? The value is minimal without knowing what the endpoints do and that is in API docs. In addition, another thing to update in dev portal when API changes.

This can be removed as well.

**Comment by Nazarah** [comment] 2020-04-09 06:46
@kyyberi  Redundant version number and endpoints have been removed from API Profile. About keeping the 1st expand-collapse section open, the issue is in the list of fixes and should soon be implemented. Hence closing this issue.

**Closed by Nazarah** 2020-04-09 06:46 UTC
Labels: APIs, application
